### Valid request
GET http://localhost:3000/data


### Invalid 404 request
GET http://localhost:3000/non-existent


# Level dalej:
# testy endpointów:
# https://www.npmjs.com/package/supertest
# https://vitest.dev/guide/


### Valid request with .env
GET http://localhost:3030/data


### Invalid request with .env
GET http://localhost:3030/data-non-existent

### Invalid request with .env
POST http://localhost:3030/data-non